### ISSUE TITLE
[BUG] Exposure Notifications not enabled MIUI 12

### ISSUE THREAD

**Issue by Fner-hjw** [immuni-app/immuni-app-android#148]
Exposure Notifications can't be turned on on MIUI 12

After installing the app, turning on Bluetooth and GPS, the app says the Exposure Notifications aren't enabled also if in the Google settings they're enabled.

1. Go to Immumi, Enable Covid-19 Exposure Notifications page
2. Click on 'Allow'
3. See error

Expected behaviour

Turn on the Notifications

- Device: MI8
- OS: 10 MIUI 12
- Version 1.0.0

**Comment by Fner-hjw** [comment]
Update:
If I set the system languages to Italian and then try to activate the Exposure Notifications it works but I suppose it should work with English language as well

**Comment by AlainCh2** [comment]
nobody knows where "expoasure notification" is hidden

I have Bt always on.

I can start the app shutting it down... B U T :....

Next time I restart the App the issue is back.

(stupid programmers)

**Comment by mlocati** [comment]
> stupid programmers

Is this a constructive comment? Please, avoid that, GitHub is not Facebook

**Comment by AlainCh2** [comment]
Update : Stupid programming is when you know a fact and you tend to ignore it.

Huawei conglomeration is still under Trump Ban.
That means Hawei cells and Honor for what I know.


A programmer knowing it's job will post a sensible an meaningful error,
 instead of a generic one "confusing all users"

Here is the answer:
https://support.google.com/android/thread/29434011?hl=en&msgid=29434011

May be the world changed from '76 but not the way IT act and react.
(now I'm happily retired - but I still lash at IT stupidity as an IT - sorry for that)

**Comment by mlocati** [comment]
Being in IT since 1986, I can for sure assure you that being called stupid leads to nothing but bitterness (and causes useless discussions like this one).
Sure, there are problems caused by the mess of Android device configurations out there. So, let's save the app authors some time, and let's skip offenses (yep, calling someone stupid is an offense).

**Comment by marcouberti** [comment]
Hi @AlainCh2, thank you for your contribution. 
You have to consider that there are Huawei devices with the Google Play Store and all the Play Services installed and there is no reason why these devices shouldn't work as expected.
If you want to collaborate and help us figure out the issue you can send us a bugreport (adb bugreport). Thank you.

**Comment by AlainCh2** [comment]
@marcouberti 
I have an Honor View 10 (2018) 
 the Google Play Store was there from the beginning...
 that doesn't mean I do receive automatically updates!!

They have to be released by Honor&Huawei first, to reach my phone.
So far this "exposure Notification thing" didn't  :-D

@Mlocati
Normally a sting obtain some results,
 while a courteous request is prone to be ignored.

**Comment by marcouberti** [comment]
@AlainCh2 I understand your point, but in a normal and expected scenario the Google Play Services should stop the user before doing the onboarding doing these checks:

- are google play services updated?
- is the exposure notification module installed?
- is an app updated required ?

If you pass all these checks there should be no reason for the app to fail enabling the exposure notification. Unfortunately this is happening and we (Google, Huawei and the immuni team) are trying to figure it out as fast as possible.

**Comment by AlainCh2** [comment]
@marcouberti 
You disclosed your working with Huawei ?

That's great and I suppose it's the only right  things to do.

So far then good job!

Nonetheless  may I suggest we solve immediately the issue?
 ....change that silly error message 
!! to something meaningful !!

The problem is not the App not working, per se,
the problem is : private users get confused and not informed correctly !!

**Comment by AlainCh2** [comment]
@marcouberti
@mlocati 

Downloaded the new update right now
... without having  to do anything not even a new setup ...
the App Immuni work flawlessly, now.

A big thanks for everybody involved.

One small suggestion?

> Put into the Home screen:  "Immuni is up & running for you "

That allow the user to be sure the app's working.
(there is no other way to know if it's active)

**Comment by Jabo-SCO** [comment]
Hey, any chance you guys could share how you made Immuni work with MIUI? I've been talking to the devs of my country's app (Protect Scotland) as it does not work in MIUI. I'd like to submit a PR on their repo with a fix.
