### ISSUE TITLE
[FEAT] Add support for Huawei Contact Shield

### ISSUE THREAD

**Issue by ilovelinux** [immuni-app/immuni-app-android#302]
**Is your feature request related to a problem? Please describe it.**
Huawei users can't user Immuni due to the lack of Google Services.
Related to #260 and https://github.com/immuni-app/immuni-documentation/issues/146

**Describe the solution you'd like**
Use new Huawei Contact Shield APIs: https://developer.huawei.com/consumer/en/doc/development/Contact-Shield-V1/introduction-0000001050738511-V1

**Comment by rawmain** [comment]
Hello @ilovelinux 

Since yesterday (January 29, 2021) the official version of Immuni is available on the Huawei AppGallery too .

App page | https://appgallery.huawei.com/#/app/C103200367
----------|---------------------------------------------------------
Release | 2.2.1
Build | #2300001

Such release is different from the 2.2.1 release update (build #2325093) available on Google Play Store. 

It supports indeed not only GMS GAEN API, but also HMS ContactShield API (thanks to @FStranieri development). 

Therefore, it can be used also on latest Honor/Huawei GSM uncertified devices. Requirement : Huawei Mobile Services / HMS Core (com.huawei.hwid) version 5.1.0.300 or higher.

These are some test screenshots with such release on a Huawei P40 Pro (ELS-NX9) - running EMUI11.0 based on Android 10.

![2021-01-29 (2)](https://user-images.githubusercontent.com/18743336/106357132-7f330080-6304-11eb-8472-fb4fd5ed6b02.png)
.
![2021-01-29 (3)](https://user-images.githubusercontent.com/18743336/106357300-8c042400-6305-11eb-8ccb-67da2aa7d59c.png)
.
![2021-01-29 (4)](https://user-images.githubusercontent.com/18743336/106357306-97574f80-6305-11eb-8f24-de1aa614a44f.png)
.
![2021-01-29 (5)](https://user-images.githubusercontent.com/18743336/106357311-a50cd500-6305-11eb-90ec-4cd49df90802.png)
