### ISSUE TITLE
Exposure notification not asked 

### ISSUE THREAD

**Issue by spectrumIG** [immuni-app/immuni-app-android#8]
**Describe the bug**

When onboarding after the Choose City step when user is asked for Exposure notification clicking on "Consenti" show the exception toast and the app can't go on and nothing's showing on screen.

**Expected behaviour**
The app should show a dialog to ask for something

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Samsung A-50
- OS: Android 10
- Version 1.0

**Additional context**
The error seems to be generated by an exception in startExposureNotification method inside OnBoardingViewModel. Putting a breakpoint at line 155 when launching the coroutine, an exception is risen with this message:

`ApiException: 17: API: Nearby.EXPOSURE_NOTIFICATION_API is not available on this device. Connection failed with: ConnectionResult{statusCode=UNKNOWN_ERROR_CODE(39507), resolution=null, message=null} 
atcom.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.2.1:4)
atcom.google.android.gms.common.api.internal.ApiExceptionMapper.getException(com.google.android.gms:play-services-base@@17.2.1:2)`

Maybe is a device problem but I wasn't notified of anything at all.

**Comment by mattcianna** [comment]
I have the same issue. Oneplus 8 Pro, Android 10

**Comment by spectrumIG** [comment]
Maybe this : [https://github.com/google/exposure-notifications-android/issues/3](link)  has something to do? Hope it helps :)

**Comment by nautilor** [comment]
Same on Oppo Reno 2, Android 10

**Comment by sabas** [comment]
Have you received the play services update? The API they build upon should be distributed by Google in that package if I understood correctly...

**Comment by spectrumIG** [comment]
@sabas I thought was something like that but i checked with my devices play service version and it seems updated. I tried to update with play store but nothing's showing on....maybe is just a delay on update?

**Comment by nautilor** [comment]
@sabas updated the play services on version 20.15.40 from apk store, the play store one was a little bit older with version 20.15.16, I'm part of the beta for play services but nothing

**Comment by sabas** [comment]
I have as well the 20.15.16 version, I see from the play store it was updated on May 4th, the release announcement was on 20th... Mine is a guess only, I haven't checked the app :-)

**Comment by Gianlupisa1** [comment]
i have the same issue: exposure notifications error

**Comment by mlocati** [comment]
[Google Exposure Notification](https://www.google.com/covid19/exposurenotifications/) is not in General Availability stage, it's only available to public health agencies.

**Comment by Gianlupisa1** [comment]
@mlocati does that mean that we can't have access in any way?

**Comment by mlocati** [comment]
It seems so...see also https://github.com/google/exposure-notifications-android/issues/3#issuecomment-633505989

**Comment by Talebian12** [comment]
From README:
`Please note that Google restricts the usage of the Exposure Notification API to government entities or developers approved by a government entity to develop an application on behalf of a government for COVID-19 response efforts. Full details are in the Additional Terms document. Otherwise, you may build and use the application, but you will not be able to use the underlying Exposure Notification system.`

**Comment by spectrumIG** [comment]
I see. My bad,I should have read more carefully the Readme before opening
the bug. I'm sorry.

Il lun 25 mag 2020, 13:09 Talebian <notifications@github.com> ha scritto:

**Comment by mlocati** [comment]
> ,I should have read more carefully the Readme before opening the bug

IMHO it's a good point: developers should have access to the Exposure Notification stuff, even if it's still in beta.

**Comment by spectrumIG** [comment]
@mlocati I agree with you but since it's a "Google matter" we can't complain with Immuni developers for this and having some experience with Google lib i can say that there's nothing more we can do on that side. Not reading the readme on my side has just make some people wasting time on a issue that was already been processed by developers.  :)

**Comment by powext** [comment]
Since the APK must be signed with a key of an authority that has been approved by Google there is no way to test the APIs in a non-release version.
A nice thing to have would be a "fake" class like [FakeAppUpdateManager ](https://developer.android.com/reference/com/google/android/play/core/appupdate/testing/FakeAppUpdateManager.html), useful while testing.

Maybe we'll have a response in this [thread ](https://github.com/google/exposure-notifications-android/issues/8) by google.

**Comment by spectrumIG** [comment]
@powext yes, actually I was looking for that in test module. I saw that thread you posted but since today no one has answerend or posted an official statement. We will see.

**Comment by immuniopensource** [comment]
> I see. My bad,I should have read more carefully the Readme before opening the bug. I'm sorry. 

Hi @spectrumIG and thank you for opening this issue. As you and others mentioned, this is not a bug but it's something not directly under the developers' control. However, since there are links of interest for everyone in some messages, I would like to leave this open for a while. Could you please just change the title of the issue and remove the BUG keyword? Thanks a lot for your help! :+1:

**Comment by spectrumIG** [comment]
@immuniopensource done. Thanks for the reply and sorry again for opening the issue
