### ISSUE TITLE
[BUG] The service is shown as active even after disabling exposure notifications

### ISSUE THREAD

**Issue by grausof** [immuni-app/immuni-app-android#86]
If I disable exposure notifications on Android settings, I keep seeing the screen that Immuni service is active on the home page (only if I don't close the app via task manager).

**To Reproduce**

1. Open the immune app, verify that it is active and leave the app in background
2. Go to Android settings, Google,  Exposure notifications to covid-19 and disable the exposure notifications
3. Open the Immuni app again

**Expected behaviour**
I expect that having disabled the exposure log, Immuni should say that the service is not active, but instead I keep seeing that the service is active. If I close and reopen the app from the task manager, the problem is solved.

**Screenshots**

![IMMUNI BUG](https://user-images.githubusercontent.com/442709/83147850-7f855700-a0f8-11ea-82bb-5755709a30ef.gif)

**Smartphone:**
- Device: Samsung A40
- OS: Android 10

**Additional context**
Same problem on iOS simulator

**Comment by bolismauro** [comment]
On iOS there is a well-known bug where the manager doesn't return the new state in this specific case
@LorDisturbia

**Comment by LorDisturbia** [comment]
Regarding iOS:
- There was a bug in the previous beta of the ExposureNotification framework that made it behave like the bug describes: [ENManager.authorizationStatus](https://developer.apple.com/documentation/exposurenotification/enmanager/3583721-authorizationstatus) would not be updated in the case described.

They fixed it in the final release, though, as I just verified again on my physical device.

The reason you see this behavior on the iOS simulator is that the whole ExposureNotification framework is mocked on the simulator (it wouldn't work otherwise, and you wouldn't be able to test the UI). You can see the relevant core [here](https://github.com/immuni-app/immuni-app-ios/blob/master/Modules/ImmuniExposureNotification/ExposureNotificationManager.swift#L33)
